apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-hostpath
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localstorage
  hostPath:
    path: /home/data/