apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  labels:
    app.kubernetes.io/name: webapp-color
    app.kubernetes.io/component: webapp-color
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      value: "red"
    name: webapp-color
    ports:
    - containerPort: 8080
      protocol: TCP
