apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-env-from-secret
  labels:
    app.kubernetes.io/name: webapp-color-env-from-secret
    app.kubernetes.io/component: webapp-color-env-from-secret
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    name: webapp-color-env-from-secret
    env:
    - name: APP_COLOR
      valueFrom: 
        configMapKeyRef:
          name: webapp-color-config
          key: APP_COLOR
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    - name: certs
      mountPath: /etc/nginx/certs/
      readOnly: true
    ports:
    - containerPort: 80
    - containerPort: 443
  volumes:
  - name: config
    configMap:
      name: webapp-color-config
      items:
      - key: APP_COLOR
  - name: certs
    secret:
      secretName: webapp-color-https