apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-env-from-secret
  labels:
    app.kubernetes.io/name: webapp-color-env-from-secret
    app.kubernetes.io/component: webapp-color-env-from-secret
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      valueFrom:
        secretKeyRef:
          name: webapp-color-secret
          key: APP_COLOR
    name: webapp-color-env-from-secret
    ports:
    - containerPort: 8080
      protocol: TCP