apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-env-from-configmap
  labels:
    app.kubernetes.io/name: webapp-color-env-from-configmap
    app.kubernetes.io/component: webapp-color-env-from-configmap
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      valueFrom: 
        configMapKeyRef:
          name: webapp-color-config
          key: APP_COLOR
    name: webapp-color-env-from-configmap
    ports:
    - containerPort: 8080
      protocol: TCP